#!/usr/bin/env python3
"""Tests for the deterministic planning assembler (scripts/assemble_planning.py).

Two things are proven here:
1. An AssemblyError-free payload ALWAYS produces a zero-ERROR planning page —
   the assembler self-validates, so mechanical error classes are unreachable.
2. Judgment-level problems fail fast as AssemblyError with a precise message,
   instead of surfacing later as opaque validator ERRORs.
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from assemble_planning import (  # noqa: E402
    MINIMAL_PAYLOAD_EXAMPLE,
    AssemblyError,
    assemble_page,
    build_notes_from_pages,
    derive_notes_entry,
)
from planning_validator import DENSITY_DEFAULTS, validate_page  # noqa: E402

REFS = (REPO_ROOT / "references").resolve()


def payload(**over):
    p = copy.deepcopy(MINIMAL_PAYLOAD_EXAMPLE)
    p.update(over)
    return p


# --- guarantee: assembled output is always validator-clean ------------------

def test_minimal_payload_is_valid():
    page, dropped = assemble_page(payload(), REFS)
    assert validate_page(page, REFS).errors == []
    assert dropped == []


def test_body_string_is_coerced_to_list():
    page, _ = assemble_page(payload(), REFS)
    # payload card[0].body was a bare string
    assert page["cards"][0]["body"] == [
        "Weekly active users doubled in the quarter after launch."]


def test_card_ids_are_autogenerated():
    p = payload()
    for c in p["cards"]:
        c.pop("card_id", None)
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["card_id"] == "s3-anchor-1"
    assert page["cards"][1]["card_id"] == "s3-support-2"


def test_density_contract_is_filled_from_validator_defaults():
    page, _ = assemble_page(payload(), REFS)
    dc = page["density_contract"]
    for k, v in DENSITY_DEFAULTS["medium"].items():
        assert dc[k] == v, f"{k} should match DENSITY_DEFAULTS[medium]"
    # outline-supplied fields survive
    assert dc["deck_bias"] == "balanced"
    assert dc["page_lower_bound"] == "mid_low"


def test_body_max_lines_is_capped_to_density():
    p = payload()
    p["cards"][0]["body_max_lines"] = 99          # over the medium cap of 5
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["content_budget"]["body_max_lines"] == 5
    assert validate_page(page, REFS).errors == []


def test_image_contract_is_built_both_ways():
    p = payload()
    p["cards"][1]["image"] = {
        "usage": "inline-illustration", "placement": "right-half",
        "content_description": "a chart", "source_hint": "assets/x.png"}
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["image"]["needed"] is False   # no image → null contract
    assert page["cards"][0]["image"]["usage"] is None
    assert page["cards"][1]["image"]["needed"] is True
    assert page["cards"][1]["image"]["usage"] == "inline-illustration"


def test_unresolvable_refs_are_dropped_not_errored():
    p = payload()
    p["resources"]["block_refs"] = ["worksheet", "does-not-exist", "text"]
    page, dropped = assemble_page(p, REFS)
    assert page["resources"]["block_refs"] == ["worksheet"]
    assert "block_refs:does-not-exist" in dropped
    assert validate_page(page, REFS).errors == []


def test_unresolvable_card_resource_ref_is_dropped():
    p = payload()
    p["cards"][0]["resource_ref"] = {"block": "does-not-exist", "chart": "basic"}
    page, dropped = assemble_page(p, REFS)
    rr = page["cards"][0]["resource_ref"]
    assert rr["block"] is None                 # unresolvable → dropped
    assert rr["chart"] == "basic"              # resolvable → kept
    assert "resource_ref.block:does-not-exist" in dropped
    assert validate_page(page, REFS).errors == []


def test_workflow_metadata_and_source_guidance_are_synthesized():
    page, _ = assemble_page(payload(), REFS)
    assert page["workflow_metadata"]["planning_schema_version"] == "4.1"
    assert page["source_guidance"]  # content page always gets one


# --- fail-fast: judgment errors raise AssemblyError, not validator noise -----

def test_bad_enum_fails_fast_with_field_name():
    p = payload()
    p["cards"][0]["card_type"] = "bogus"
    with pytest.raises(AssemblyError, match="card_type"):
        assemble_page(p, REFS)


def test_skeleton_card_fails_fast():
    p = payload()
    p["cards"][0] = {"role": "anchor", "card_type": "text", "card_style": "elevated",
                     "headline": "only a headline"}
    with pytest.raises(AssemblyError, match="skeleton"):
        assemble_page(p, REFS)


def test_missing_anchor_fails_fast():
    p = payload()
    for c in p["cards"]:
        c["role"] = "support"
    with pytest.raises(AssemblyError, match="exactly one anchor"):
        assemble_page(p, REFS)


def test_single_style_content_page_fails_fast():
    p = payload()
    p["cards"][1]["card_style"] = "elevated"   # both cards elevated
    with pytest.raises(AssemblyError, match="card_styles"):
        assemble_page(p, REFS)


def test_visual_weight_out_of_range_fails_fast():
    with pytest.raises(AssemblyError, match=r"visual_weight"):
        assemble_page(payload(visual_weight=10), REFS)


def test_cross_field_combination_fails_fast_as_assembly_error():
    # dashboard density on a cover page is a valid-enum-but-invalid-combination;
    # the assembler's self-validation must surface it as a clean AssemblyError,
    # not a RuntimeError blaming the assembler.
    p = payload(page_type="cover", density_label="dashboard",
                page_lower_bound="high", page_upper_bound="dashboard")
    p.pop("layout_hint", None)          # cover doesn't take one
    p["cards"] = [p["cards"][0]]        # single card, keeps one anchor
    # the self-validate surfaces the real validator error, which names the fields
    with pytest.raises(AssemblyError, match="cannot use density_label 'dashboard'"):
        assemble_page(p, REFS)


# ── speaker-notes derivation ──────────────────────────────────────────────────

def _notes_page(slide_number: int = 1, **over) -> dict:
    """Minimal planning page dict for notes-derivation tests."""
    p: dict = {
        "slide_number": slide_number,
        "title": f"Slide {slide_number} Title",
        "page_goal": "show that adoption doubled",
        "narrative_role": "evidence",
        "cards": [
            {"role": "anchor", "headline": "2x adoption", "body": ["usage doubled"]},
            {"role": "support", "headline": "context", "body": ["details"]},
        ],
    }
    p.update(over)
    return p


def test_derive_notes_entry_first_slide_structure():
    entry = derive_notes_entry(_notes_page(slide_number=1), prev_page=None)
    assert isinstance(entry, dict)
    assert entry["slide_number"] == 1
    assert isinstance(entry["title"], str)
    assert isinstance(entry["notes"], str)


def test_derive_notes_entry_first_slide_non_empty():
    entry = derive_notes_entry(_notes_page())
    assert entry["notes"], "notes should be non-empty when page_goal is present"


def test_derive_notes_entry_first_slide_contains_page_goal():
    entry = derive_notes_entry(_notes_page(page_goal="prove the hypothesis"))
    assert "prove the hypothesis" in entry["notes"]


def test_derive_notes_entry_subsequent_slide_contains_prev_title():
    prev = _notes_page(slide_number=1, title="Previous Slide")
    curr = _notes_page(slide_number=2)
    entry = derive_notes_entry(curr, prev_page=prev)
    assert "Previous Slide" in entry["notes"]


def test_derive_notes_entry_covers_two_components():
    prev = _notes_page(slide_number=1, title="Setup Slide")
    curr = _notes_page(
        slide_number=2,
        page_goal="demonstrate ROI clearly",
        audience_takeaway="the investment pays off",
    )
    entry = derive_notes_entry(curr, prev_page=prev)
    notes = entry["notes"]
    has_goal = "demonstrate ROI clearly" in notes
    has_prev = "Setup Slide" in notes
    has_key = "the investment pays off" in notes or "2x adoption" in notes
    assert sum([has_goal, has_prev, has_key]) >= 2, (
        f"notes should cover ≥2 of 3 components, got: {notes!r}"
    )


def test_derive_notes_entry_minimal_fields():
    page = {
        "slide_number": 3,
        "title": "Minimal",
        "cards": [{"role": "anchor", "headline": "Key finding", "body": ["text"]}],
    }
    entry = derive_notes_entry(page)
    assert entry["notes"], "notes non-empty when anchor headline present"
    assert "Key finding" in entry["notes"] or entry["notes"]


def test_derive_notes_entry_empty_page_no_crash():
    page = {"slide_number": 5, "title": "Empty", "cards": []}
    entry = derive_notes_entry(page)
    assert isinstance(entry["notes"], str)


def test_derive_notes_entry_no_html_tags():
    import re
    page = _notes_page(page_goal="revenue < 5% growth (good)")
    entry = derive_notes_entry(page)
    assert not re.search(r"<[a-zA-Z]", entry["notes"]), (
        f"notes must not contain HTML open-tag patterns: {entry['notes']!r}"
    )
    assert not re.search(r"</", entry["notes"]), (
        f"notes must not contain HTML close-tag patterns: {entry['notes']!r}"
    )


def test_build_notes_from_pages_schema():
    pages = [_notes_page(1), _notes_page(2)]
    result = build_notes_from_pages(pages, "my-deck")
    assert result["schema_version"] == "1"
    assert isinstance(result["_comment"], str) and result["_comment"]
    assert isinstance(result["slides"], list)


def test_build_notes_from_pages_count():
    pages = [_notes_page(1), _notes_page(2), _notes_page(3)]
    result = build_notes_from_pages(pages, "deck")
    assert len(result["slides"]) == 3
    for entry in result["slides"]:
        assert "slide_number" in entry
        assert "title" in entry
        assert "notes" in entry


def test_build_notes_from_pages_order():
    pages = [_notes_page(3), _notes_page(1), _notes_page(2)]
    result = build_notes_from_pages(pages, "deck")
    numbers = [e["slide_number"] for e in result["slides"]]
    assert numbers == sorted(numbers), "entries should be sorted by slide_number"


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
