#!/usr/bin/env python3
"""Tests for the deterministic planning assembler (scripts/assemble_planning.py).

Two things are proven here:
1. An AssemblyError-free payload ALWAYS produces a zero-ERROR planning page —
   the assembler self-validates, so mechanical error classes are unreachable.
2. Judgment-level problems fail fast as AssemblyError with a precise message,
   instead of surfacing later as opaque validator ERRORs.
"""

from __future__ import annotations

import copy
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "scripts"))

from assemble_planning import (  # noqa: E402
    MINIMAL_PAYLOAD_EXAMPLE,
    AssemblyError,
    assemble_page,
)
from planning_validator import DENSITY_DEFAULTS, validate_page  # noqa: E402

REFS = (REPO_ROOT / "references").resolve()


def payload(**over):
    p = copy.deepcopy(MINIMAL_PAYLOAD_EXAMPLE)
    p.update(over)
    return p


# --- guarantee: assembled output is always validator-clean ------------------

def test_minimal_payload_is_valid():
    page, dropped = assemble_page(payload(), REFS)
    assert validate_page(page, REFS).errors == []
    assert dropped == []


def test_body_string_is_coerced_to_list():
    page, _ = assemble_page(payload(), REFS)
    # payload card[0].body was a bare string
    assert page["cards"][0]["body"] == [
        "Weekly active users doubled in the quarter after launch."]


def test_card_ids_are_autogenerated():
    p = payload()
    for c in p["cards"]:
        c.pop("card_id", None)
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["card_id"] == "s3-anchor-1"
    assert page["cards"][1]["card_id"] == "s3-support-2"


def test_density_contract_is_filled_from_validator_defaults():
    page, _ = assemble_page(payload(), REFS)
    dc = page["density_contract"]
    for k, v in DENSITY_DEFAULTS["medium"].items():
        assert dc[k] == v, f"{k} should match DENSITY_DEFAULTS[medium]"
    # outline-supplied fields survive
    assert dc["deck_bias"] == "balanced"
    assert dc["page_lower_bound"] == "mid_low"


def test_body_max_lines_is_capped_to_density():
    p = payload()
    p["cards"][0]["body_max_lines"] = 99          # over the medium cap of 5
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["content_budget"]["body_max_lines"] == 5
    assert validate_page(page, REFS).errors == []


def test_image_contract_is_built_both_ways():
    p = payload()
    p["cards"][1]["image"] = {
        "usage": "inline-illustration", "placement": "right-half",
        "content_description": "a chart", "source_hint": "assets/x.png"}
    page, _ = assemble_page(p, REFS)
    assert page["cards"][0]["image"]["needed"] is False   # no image → null contract
    assert page["cards"][0]["image"]["usage"] is None
    assert page["cards"][1]["image"]["needed"] is True
    assert page["cards"][1]["image"]["usage"] == "inline-illustration"


def test_unresolvable_refs_are_dropped_not_errored():
    p = payload()
    p["resources"]["block_refs"] = ["worksheet", "does-not-exist", "text"]
    page, dropped = assemble_page(p, REFS)
    assert page["resources"]["block_refs"] == ["worksheet"]
    assert "block_refs:does-not-exist" in dropped
    assert validate_page(page, REFS).errors == []


def test_unresolvable_card_resource_ref_is_dropped():
    p = payload()
    p["cards"][0]["resource_ref"] = {"block": "does-not-exist", "chart": "basic"}
    page, dropped = assemble_page(p, REFS)
    rr = page["cards"][0]["resource_ref"]
    assert rr["block"] is None                 # unresolvable → dropped
    assert rr["chart"] == "basic"              # resolvable → kept
    assert "resource_ref.block:does-not-exist" in dropped
    assert validate_page(page, REFS).errors == []


def test_workflow_metadata_and_source_guidance_are_synthesized():
    page, _ = assemble_page(payload(), REFS)
    assert page["workflow_metadata"]["planning_schema_version"] == "4.1"
    assert page["source_guidance"]  # content page always gets one


# --- fail-fast: judgment errors raise AssemblyError, not validator noise -----

def test_bad_enum_fails_fast_with_field_name():
    p = payload()
    p["cards"][0]["card_type"] = "bogus"
    with pytest.raises(AssemblyError, match="card_type"):
        assemble_page(p, REFS)


def test_skeleton_card_fails_fast():
    p = payload()
    p["cards"][0] = {"role": "anchor", "card_type": "text", "card_style": "elevated",
                     "headline": "only a headline"}
    with pytest.raises(AssemblyError, match="skeleton"):
        assemble_page(p, REFS)


def test_missing_anchor_fails_fast():
    p = payload()
    for c in p["cards"]:
        c["role"] = "support"
    with pytest.raises(AssemblyError, match="exactly one anchor"):
        assemble_page(p, REFS)


def test_single_style_content_page_fails_fast():
    p = payload()
    p["cards"][1]["card_style"] = "elevated"   # both cards elevated
    with pytest.raises(AssemblyError, match="card_styles"):
        assemble_page(p, REFS)


def test_visual_weight_out_of_range_fails_fast():
    with pytest.raises(AssemblyError, match=r"visual_weight"):
        assemble_page(payload(visual_weight=10), REFS)


def test_cross_field_combination_fails_fast_as_assembly_error():
    # dashboard density on a cover page is a valid-enum-but-invalid-combination;
    # the assembler's self-validation must surface it as a clean AssemblyError,
    # not a RuntimeError blaming the assembler.
    p = payload(page_type="cover", density_label="dashboard",
                page_lower_bound="high", page_upper_bound="dashboard")
    p.pop("layout_hint", None)          # cover doesn't take one
    p["cards"] = [p["cards"][0]]        # single card, keeps one anchor
    # the self-validate surfaces the real validator error, which names the fields
    with pytest.raises(AssemblyError, match="cannot use density_label 'dashboard'"):
        assemble_page(p, REFS)


if __name__ == "__main__":
    raise SystemExit(pytest.main([__file__, "-q"]))
